# Generated by Django 3.2.12 on 2023-03-05 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginconfiguration',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channel.channel'),
        ),
    ]
