# Generated by Django 3.2.12 on 2023-03-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('plugins', '0002_pluginconfiguration_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginconfiguration',
            name='identifier',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='pluginconfiguration',
            unique_together={('identifier', 'channel')},
        ),
    ]
