version: "3.8"

services:
  web:
    build: ./
    command: gunicorn portal.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - portal-db:/var/lib/postgresql/data/
    ports:
      - 1234:5432
    environment:
      - POSTGRES_USER=portal
      - POSTGRES_PASSWORD=portal
      - POSTGRES_DB=portal

  redis:
    image: library/redis:7.0-alpine
    restart: unless-stopped
    volumes:
      - portal-redis:/data

volumes:
  portal-db:
    driver: local
  portal-redis:
    driver: local
