version: "3.8"

services:
  redis:
    image: redis:7.2.4-alpine3.19
    restart: unless-stopped
    volumes:
      - portal-redis:/data

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - app:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env

  celery-worker:
    build:
      context: .
    command: celery -A portal worker --loglevel=info
    volumes:
      - app:/app
    depends_on:
      - django
      - redis
    env_file:
      - ./.env

  celery-beat:
    build:
      context: .
    command: celery -A portal beat --loglevel=info
    volumes:
      - app:/app
    depends_on:
      - django
      - redis
    env_file:
      - ./.env

volumes:
  app:
    driver: local
  portal-redis:
    driver: local
