# Generated by Django 3.2.12 on 2022-09-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
    ]
