# Generated by Django 3.2.12 on 2022-07-27 23:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_document_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='document',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
    ]
