# Generated by Django 4.2.3 on 2023-09-09 16:11

from django.db import migrations, models
import django.db.models.deletion
import portal.document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True)),
                ("expires", models.BooleanField(default=False)),
                (
                    "load_type",
                    models.CharField(
                        choices=[
                            ("empty", "empty"),
                            ("cnep", "cnep"),
                            ("cnd", "cnd"),
                            ("cndt", "cndt"),
                            ("fgts", "fgts"),
                            ("sefaz_mg", "sefaz_mg"),
                            ("sefaz_sp", "sefaz_sp"),
                            ("tcu", "tcu"),
                            ("mei", "mei"),
                            ("jucesp", "jucesp"),
                            ("cnpj", "cnpj"),
                        ],
                        default="empty",
                        max_length=256,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "permissions": (("manage_documents", "Manage documents."),),
            },
        ),
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(upload_to=portal.document.models.get_upload_path),
                ),
                ("begin_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Aguardando"),
                            ("approved", "Aprovado"),
                            ("refused", "Recusado"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="document.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "permissions": (("manage_documents", "Manage documents."),),
            },
        ),
        migrations.CreateModel(
            name="DocumentLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendendte"),
                            ("success", "Bem sucedido"),
                            ("error", "Erro"),
                        ],
                        default="pending",
                        max_length=256,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document.document",
                    ),
                ),
                (
                    "document_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document.documentfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="document",
            name="default_file",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="document.documentfile",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="entry.entry",
            ),
        ),
    ]
