# Generated by Django 3.2.18 on 2023-03-08 00:17

from django.db import migrations, models
import portal.document.models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0003_alter_documentfile_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfile",
            name="file",
            field=models.FileField(upload_to=portal.document.models.get_upload_path),
        ),
    ]
