# Generated by Django 3.2.18 on 2023-03-10 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0006_documentfile_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfile",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="document.document",
            ),
        ),
    ]
