# Generated by Django 3.2.18 on 2023-04-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20230310_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='load_type',
            field=models.CharField(blank=True, choices=[('consult_correctional_negative_certificate', 'Certidão Negativa Correcionalo')], max_length=256),
        ),
    ]
