# Generated by Django 3.2.18 on 2023-04-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_alter_document_load_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='load_type',
            field=models.CharField(choices=[('empty', 'empty'), ('correctional_negative_certificate', 'correctional_negative_certificate'), ('labor_debit_clearance_certifiacate', 'labor_debit_clearance_certifiacate'), ('employer_regularity_fgts', 'employer_regularity_fgts')], default='empty', max_length=256),
        ),
    ]
