# Generated by Django 3.2.18 on 2023-04-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_alter_document_load_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='load_type',
            field=models.CharField(choices=[('empty', 'empty'), ('cnep', 'cnep'), ('cnd', 'cnd'), ('cndt', 'cndt'), ('fgts', 'fgts'), ('sefaz_mg', 'sefaz_mg'), ('sefaz_sp', 'sefaz_sp')], default='empty', max_length=256),
        ),
    ]
