# Generated by Django 3.2.18 on 2023-04-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0017_alter_document_load_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentload",
            name="error_message",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
