# Generated by Django 3.2.18 on 2023-04-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0021_alter_document_load_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="publication_date",
        ),
    ]
