# Generated by Django 3.2.18 on 2023-06-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0022_remove_document_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='load_type',
            field=models.CharField(choices=[('empty', 'empty'), ('cnep', 'cnep'), ('cnd', 'cnd'), ('cndt', 'cndt'), ('fgts', 'fgts'), ('sefaz_mg', 'sefaz_mg'), ('sefaz_sp', 'sefaz_sp'), ('tcu', 'tcu'), ('mei', 'mei'), ('jucesp', 'jucesp'), ('cnpj', 'cnpj')], default='empty', max_length=256),
        ),
    ]
