# Generated by Django 3.2.18 on 2023-06-23 17:24

from django.db import migrations, models

from portal.document import DocumentLoadOptions


def remove_invalid_expirations(apps, schema_editor):
    Document = apps.get_model("document", "Document")

    non_expirable = [DocumentLoadOptions.JUCESP, DocumentLoadOptions.CNPJ]

    for document in Document.objects.filter(load_type__in=non_expirable):
        document.expires = False
        document.save()

    for document in Document.objects.exclude(load_type__in=non_expirable):
        document.expires = True
        document.save()


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0023_alter_document_load_type"),
    ]

    operations = [migrations.RunPython(remove_invalid_expirations)]
