# Generated by Django 3.2.12 on 2022-09-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='entry_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_type',
            new_name='type',
        ),
    ]
