# Generated by Django 4.2.3 on 2023-12-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0003_auto_20231226_1528"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vehicle", "A communitation vehicle"),
                    ("provider", "A service provider"),
                ],
                max_length=24,
                null=True,
            ),
        ),
    ]
