# Generated by Django 3.2.18 on 2023-03-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_alter_entry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('vehicle', 'A communitation vehicle'), ('provider', 'A service provider')], default='vehicle', max_length=24),
            preserve_default=False,
        ),
    ]
