# Generated by Django 4.2.3 on 2024-01-16 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0004_alter_entry_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="type",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="type",
        ),
    ]
