# Generated by Django 3.2.18 on 2023-03-31 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_consult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='success',
        ),
    ]
