# Generated by Django 3.2.18 on 2023-03-31 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_remove_consult_success'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consult',
            options={'ordering': ['-created']},
        ),
    ]
