# Generated by Django 3.2.18 on 2023-04-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0008_alter_consult_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
