# Generated by Django 3.2.18 on 2023-04-29 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0001_initial"),
        ("entry", "0009_entry_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="active",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="publication_date",
        ),
        migrations.CreateModel(
            name="EntryChannelListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_listings",
                        to="channel.channel",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_listings",
                        to="entry.entry",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("entry", "channel")},
            },
        ),
    ]
