# Generated by Django 3.2.18 on 2023-04-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0010_auto_20230429_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrychannellisting',
            old_name='active',
            new_name='is_active',
        ),
    ]
