# Generated by Django 3.2.18 on 2023-05-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0011_rename_active_entrychannellisting_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='entries', to='entry.Category'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.category'),
        ),
    ]
