# Generated by Django 3.2.18 on 2023-05-04 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0013_auto_20230504_1500"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="entry.category",
            ),
        ),
    ]
