# Generated by Django 3.2.18 on 2023-05-04 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('entry', '0014_alter_entry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrychannellisting',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_listings', to='channel.channel'),
        ),
    ]
