# Generated by Django 3.2.18 on 2023-05-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0015_alter_entrychannellisting_channel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="category",
        ),
    ]
