# Generated by Django 3.2.18 on 2023-05-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0016_remove_entry_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='address',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='phone',
        ),
    ]
