# Generated by Django 4.2.10 on 2024-05-01 17:24

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimeToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="document.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT_CREATED", "document_created"),
                            ("DOCUMENT_UPDATED", "document_updated"),
                            ("DOCUMENT_DELETED", "document_deleted"),
                            ("DOCUMENT_RECEIVED", "document_received"),
                            ("DOCUMENT_APPROVED", "document_approved"),
                            ("DOCUMENT_DECLINED", "document_declined"),
                            ("DOCUMENT_REQUESTED", "document_requested"),
                            ("DOCUMENT_LOADED_FROM_API", "document_loaded_from_api"),
                            ("DOCUMENT_LOADED_FAIL", "document_loaded_fail"),
                            ("ENTRY_CREATED", "entry_created"),
                            ("ENTRY_UPDATED", "entry_updated"),
                            ("ENTRY_DELETED", "entry_deleted"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("user_email", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "document_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="document.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "permissions": (("manage_events", "Manage events."),),
            },
        ),
    ]
