# Generated by Django 3.2.18 on 2023-03-09 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0004_alter_documentfile_file"),
        ("event", "0003_onetimetoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimetoken",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to="document.document",
            ),
        ),
    ]
