# Generated by Django 4.2.3 on 2023-09-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0011_auto_20230513_1325"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-date"],
                "permissions": (("manage_events", "Manage events."),),
            },
        ),
    ]
