# Generated by Django 4.2.10 on 2024-05-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=250, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("entry_type", "Entry Type")], max_length=50
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("dropdown", "Dropdown"),
                            ("multiselect", "Multi Select"),
                            ("file", "File"),
                            ("plain-text", "Plain Text"),
                            ("swatch", "Swatch"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("reference", "Referência"),
                        ],
                        default="dropdown",
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        choices=[("entry", "Entry")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("value_required", models.BooleanField(blank=True, default=False)),
                ("visible_in_website", models.BooleanField(blank=True, default=True)),
                (
                    "filterable_in_website",
                    models.BooleanField(blank=True, default=False),
                ),
                (
                    "filterable_in_dashboard",
                    models.BooleanField(blank=True, default=False),
                ),
                ("website_search_position", models.IntegerField(blank=True, default=0)),
                ("available_in_grid", models.BooleanField(blank=True, default=False)),
            ],
            options={
                "ordering": ("name",),
                "permissions": (("manage_attributes", "Manage attributes."),),
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(db_index=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=250)),
                ("value", models.CharField(blank=True, default="", max_length=100)),
                ("slug", models.SlugField(allow_unicode=True, max_length=255)),
                ("file_url", models.URLField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("plain_text", models.TextField(blank=True, null=True)),
                ("boolean", models.BooleanField(blank=True, null=True)),
                ("date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="attribute.attribute",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="entry.entry",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("slug", "attribute")},
            },
        ),
        migrations.CreateModel(
            name="AttributeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributeentry",
                        to="attribute.attribute",
                    ),
                ),
                (
                    "entry_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributeentry",
                        to="entry.entrytype",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("attribute", "entry_type")},
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="entry_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="entry_attributes",
                through="attribute.AttributeEntry",
                to="entry.entrytype",
            ),
        ),
        migrations.CreateModel(
            name="AssignedEntryAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributevalues",
                        to="entry.entry",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entryvalueassignment",
                        to="attribute.attributevalue",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("value", "entry")},
            },
        ),
    ]
