# Generated by Django 4.2.3 on 2023-12-26 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0003_auto_20231226_1528"),
        ("attribute", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributeentry",
                        to="attribute.attribute",
                    ),
                ),
                (
                    "entry_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributeentry",
                        to="entry.entrytype",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("attribute", "entry_type")},
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="entry_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="entry_attributes",
                through="attribute.AttributeEntry",
                to="entry.entrytype",
            ),
        ),
    ]
