# Generated by Django 3.2.18 on 2023-03-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevalue",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="entry_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vehicle", "vehicle"),
                    ("provider", "provider"),
                    ("vehicle_and_provider", "vehicle and provider"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
