# Generated by Django 3.2.18 on 2023-03-20 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_auto_20230316_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ('name',)},
        ),
    ]
