# Generated by Django 4.2.3 on 2023-12-26 21:36

import django.db.models.deletion
from django.db import migrations, models
from django_tenants.utils import schema_context


def migrate_assigned_entry_attribute_value(apps, schema_editor):
    AssignedEntryAttributeValue = apps.get_model(
        "attribute", "AssignedEntryAttributeValue"
    )
    Client = apps.get_model("customer", "Client")

    clients = Client.objects.exclude(schema_name="public")

    for client in clients:
        with schema_context(client.schema_name):
            assigments = AssignedEntryAttributeValue.objects.all()
            for assigment in assigments:
                assigment.entry = assigment.assignment.entry
                assigment.save()


class Migration(migrations.Migration):
    dependencies = [
        ("entry", "0003_auto_20231226_1528"),
        ("attribute", "0003_auto_20231226_1822"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assigneddocumentattributevalue",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="assigneddocumentattributevalue",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="assigneddocumentattributevalue",
            name="value",
        ),
        migrations.AlterUniqueTogether(
            name="assignedentryattributevalue",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="attribute",
            name="assigned_documents",
        ),
        migrations.AddField(
            model_name="assignedentryattributevalue",
            name="entry",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributevalues",
                to="entry.entry",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="entity_type",
            field=models.CharField(
                blank=True, choices=[("entry", "Entry")], max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="type",
            field=models.CharField(
                choices=[("entry_type", "Entry Type")], max_length=50
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignedentryattributevalue",
            unique_together={("value", "entry")},
        ),
        migrations.DeleteModel(
            name="AssignedDocumentAttribute",
        ),
        migrations.DeleteModel(
            name="AssignedDocumentAttributeValue",
        ),
        migrations.RunPython(migrate_assigned_entry_attribute_value),
    ]
