# Generated by Django 3.2.18 on 2023-03-21 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0004_auto_20230320_1918"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignedDocumentAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentvalueassignment",
                        to="attribute.assigneddocumentattribute",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentvalueassignment",
                        to="attribute.attributevalue",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("value", "assignment")},
            },
        ),
        migrations.CreateModel(
            name="AssignedEntryAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entryvalueassignment",
                        to="attribute.assignedentryattribute",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entryvalueassignment",
                        to="attribute.attributevalue",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("value", "assignment")},
            },
        ),
        migrations.DeleteModel(
            name="AssignedProductAttributeValue",
        ),
        migrations.RemoveField(
            model_name="assigneddocumentattribute",
            name="values",
        ),
        migrations.RemoveField(
            model_name="assignedentryattribute",
            name="values",
        ),
        migrations.AddField(
            model_name="assigneddocumentattribute",
            name="values",
            field=models.ManyToManyField(
                blank=True,
                related_name="documentassignments",
                through="attribute.AssignedDocumentAttributeValue",
                to="attribute.AttributeValue",
            ),
        ),
        migrations.AddField(
            model_name="assignedentryattribute",
            name="values",
            field=models.ManyToManyField(
                blank=True,
                related_name="entryassignments",
                through="attribute.AssignedEntryAttributeValue",
                to="attribute.AttributeValue",
            ),
        ),
    ]
