# Generated by Django 4.2.3 on 2023-12-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0003_auto_20231226_1528"),
        ("attribute", "0005_remove_assignedentryattributevalue_assignment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignedentryattributevalue",
            name="entry",
            field=models.ForeignKey(
                db_index=False,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributevalues",
                to="entry.entry",
            ),
            preserve_default=False,
        ),
    ]
