# Generated by Django 3.2.18 on 2023-04-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0005_auto_20230321_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ('name',), 'permissions': (('manage_attributes', 'Manage attributes.'),)},
        ),
    ]
