# Generated by Django 3.2.18 on 2023-04-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0006_alter_attribute_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='input_type',
            field=models.CharField(choices=[('dropdown', 'Dropdown'), ('multiselect', 'Multi Select'), ('file', 'File'), ('plain-text', 'Plain Text'), ('swatch', 'Swatch'), ('boolean', 'Boolean'), ('date', 'Date'), ('reference', 'Referência')], default='dropdown', max_length=50),
        ),
    ]
