# Generated by Django 4.2.3 on 2023-12-27 16:55

import django.db.models.deletion
from django.db import migrations, models
from django_tenants.utils import schema_context

from portal.attribute import AttributeType


def migrate_types(apps, schema_editor):
    Attribute = apps.get_model("attribute", "Attribute")
    Client = apps.get_model("customer", "Client")

    clients = Client.objects.exclude(schema_name="public")

    for client in clients:
        with schema_context(client.schema_name):
            attributes = Attribute.objects.all()
            for attribute in attributes:
                attribute.type = AttributeType.ENTRY_TYPE
                attribute.save()


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0006_alter_assignedentryattributevalue_entry"),
    ]

    operations = [migrations.RunPython(migrate_types)]
