# Generated by Django 3.2.18 on 2023-04-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0010_attribute_entity_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attributevalue",
            name="date",
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="entity_type",
            field=models.CharField(
                blank=True,
                choices=[("vehicle", "Veiculo"), ("provider", "Fornecedor")],
                max_length=50,
                null=True,
            ),
        ),
    ]
