# Generated by Django 4.2.3 on 2023-09-09 16:11

from django.db import migrations, models
import django.db.models.deletion
import portal.core.db.fields
import portal.core.utils.editorjs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("slug", models.SlugField(max_length=256, unique=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "content",
                    portal.core.db.fields.SanitizedJSONField(
                        blank=True,
                        null=True,
                        sanitizer=portal.core.utils.editorjs.clean_editor_js,
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channel.channel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "permissions": (("manage_sessions", "Manage sessions."),),
            },
        ),
    ]
