# Generated by Django 3.2.12 on 2022-09-23 00:22

from django.db import migrations, models
import portal.core.db.fields
import portal.core.utils.editorjs


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("slug", models.SlugField(max_length=256, unique=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "content",
                    portal.core.db.fields.SanitizedJSONField(
                        blank=True,
                        null=True,
                        sanitizer=portal.core.utils.editorjs.clean_editor_js,
                    ),
                ),
                ("date", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created"],
                "permissions": (("manage_sessions", "Manage sessions."),),
            },
        ),
    ]
