# Generated by Django 3.2.12 on 2022-06-25 17:18

from django.db import migrations

import portal.core.db.fields
import portal.core.utils.editorjs


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='content',
            field=portal.core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=portal.core.utils.editorjs.clean_editor_js),
        ),
    ]
