# Generated by Django 3.2.12 on 2022-06-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_session_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
