# Generated by Django 4.2.3 on 2023-08-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0001_initial"),
        ("session", "0003_session_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="channel.channel"
            ),
        ),
    ]
