version: "3.8"

services:
  db:
    image: postgres:16.2-alpine3.19
    volumes:
      - portal-db:/var/lib/postgresql/data/
    ports:
      - 1234:5432
    environment:
      - POSTGRES_USER=portal
      - POSTGRES_PASSWORD=portal
      - POSTGRES_DB=portal

  redis:
    image: redis:7.2.4-alpine3.19
    restart: unless-stopped
    volumes:
      - portal-redis:/data

  web:
    build:
      context: ..
      dockerfile: ./Dockerfile
    volumes:
      - app:/app
    ports:
      - 8000:8000
    env_file:
      - ../.env
    depends_on:
      - db

  celery:
    build:
      context: ..
    command: celery -A portal worker --loglevel=info
    volumes:
      - app:/app
    env_file:
      - ../.env
    depends_on:
      - web
      - redis

volumes:
  app:
    driver: local
  portal-db:
    driver: local
  portal-redis:
    driver: local
