# Generated by Django 3.2.12 on 2022-07-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-year', '-month'], 'permissions': (('manage_investments', 'Manage investments.'),)},
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='mounth',
            new_name='month',
        ),
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together={('year', 'month')},
        ),
    ]
