# Generated by Django 4.2.3 on 2023-08-22 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0001_initial"),
        ("investment", "0003_alter_investment_options_investment_channel"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="investment",
            unique_together={("year", "month", "channel")},
        ),
    ]
