name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t portal-backend .

      - name: Tag Docker image
        run: docker tag portal-backend ${{ secrets.DOCKER_USERNAME }}/portal-backend:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/portal-backend:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install EB CLI
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip3 install --upgrade pip
          pip3 install awsebcli --upgrade

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          eb configure set aws:elasticbeanstalk:application:environment AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          eb configure set aws:elasticbeanstalk:application:environment AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          eb configure set aws:elasticbeanstalk:application:environment AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

      - name: Deploy to Elastic Beanstalk
        run: eb deploy ${{ secrets.ENVIRONMENT_NAME }} --nohang
